import sys
import os
import shutil
import json

FUNCTIONS_DIR = "output"
OUTPUT_DIR = "datapack"
PACK_MCMETA = json.dumps(
    {
        "pack": {
            "description": "Generated by mcvideoholo",
            "min_format": 94,
            "max_format": 101.1,
        },
    }
)

if not os.path.isdir(FUNCTIONS_DIR):
    print("Please run main.py first!")
    sys.exit(1)

if os.path.exists(OUTPUT_DIR):
    os.removedirs(OUTPUT_DIR)

os.makedirs(OUTPUT_DIR)

with open(os.path.join(OUTPUT_DIR, "pack.mcmeta"), "w") as f:
    f.write(PACK_MCMETA)

shutil.copytree(FUNCTIONS_DIR, os.path.join(OUTPUT_DIR, "mcvideoholo", "functions"))
print(f"Done! Created Minecraft 1.21.11-26.1.2 datapack at {OUTPUT_DIR}/")
